apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  env.js: |
    window.__ENV__ = {
      TRACKING_ENDPOINT: {{ .Values.endpoints.analytics | quote }},
      CART_ENDPOINT: {{ .Values.endpoints.orders | quote }},
      GAMES_ENDPOINT: {{ .Values.endpoints.games | quote }},
      RECOMMENDATION_ENDPOINT: {{ .Values.endpoints.recommendations | quote }}
    };
