apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  env.js: |
    window.__ENV__ = {
      TRACKING_ENDPOINT: "{{ .Values.env.TRACKING_ENDPOINT | quote }}",
      CART_ENDPOINT: "{{ .Values.env.CART_ENDPOINT | quote }}",
      GAMES_ENDPOINT: "{{ .Values.env.GAMES_ENDPOINT | quote }}",
      RECOMMENDATION_ENDPOINT: "{{ .Values.env.RECOMMENDATION_ENDPOINT | quote }}"
    };
