{{- if .Values.ingress.enabled }}
# === FRONTEND INGRESS ===
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend
  annotations:
      {{- range $key, $value := .Values.ingress.annotations }}
        {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-frontend
                port:
                  number: 80
          {{- end }}
    {{- end }}
  {{- end }}

---

  {{- if .Values.backendIngress.enabled }}
# === BACKEND INGRESS ===
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    {{- range $key, $value := .Values.backendIngress.annotations }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
spec:
  ingressClassName: {{ .Values.backendIngress.className }}
  tls:
    {{- toYaml .Values.backendIngress.tls | nindent 4 }}
  rules:
    - host: {{ .Values.backendIngress.host }}
      http:
        paths:
          {{- range .Values.backendIngress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
  {{- end }}
