{{- if .Values.ingress.enabled }}
# === FRONTEND INGRESS ===
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lugx-ui-ingress
  annotations:
    {{- range $k, $v := .Values.uiIngress.annotations }}
      {{ $k }}: {{ $v | quote }}
      {{- end }}
spec:
  ingressClassName: {{ .Values.uiIngress.className }}
  rules:
    - http:
        paths:
          {{- range .Values.uiIngress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: lugx-ui
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
  {{- end }}


---

{{- if .Values.backendIngress.enabled }}
# === BACKEND INGRESS ===
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  annotations:
    {{- range $k, $v := .Values.backendIngress.annotations }}
      {{ $k }}: {{ $v | quote }}
      {{- end }}
spec:
  ingressClassName: {{ .Values.backendIngress.className }}
  rules:
    - http:
        paths:
          {{- range .Values.backendIngress.routes }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .targetService }}
                port:
                  number: {{ .targetPort }}
          {{- end }}
  {{- end }}

