replicaCount: 1

image:
  repository: adeeshadev/lugx-gaming-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: lugx.minikube.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - lugx.minikube.local
      secretName: api-lugx-tls

backendIngress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
  tls:
    - hosts:
        - api.lugx.minikube.local
      secretName: api-lugx-tls
  host: api.lugx.minikube.local
  paths:
    - path: /games
      pathType: Prefix
      serviceName: game-service-backend
      servicePort: 5001
    - path: /orders
      pathType: Prefix
      serviceName: order-service-backend
      servicePort: 5004
    - path: /recommendations
      pathType: Prefix
      serviceName: recommendation-service-backend
      servicePort: 5002
    - path: /track
      pathType: Prefix
      serviceName: analytics-service-backend
      servicePort: 5003

endpoints:
  analytics: https://api.lugx.minikube.local/track
  orders: https://api.lugx.minikube.local/orders
  games: https://api.lugx.minikube.local/games
  recommendations: https://api.lugx.minikube.local/recommendations


