replicaCount: 1

image:
  repository: adeeshadev/lugx-gaming-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: lugx.minikube.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  TRACKING_ENDPOINT: "http://tracking-service.default.svc.cluster.local:5003/track"
  CART_ENDPOINT: "http://order-service.default.svc.cluster.local:5004/orders"
  GAMES_ENDPOINT: "http://game-service-backend.default.svc.cluster.local:5001/games"
  RECOMMENDATION_ENDPOINT: "http://recommendation-service.default.svc.cluster.local:5002/recommendations"

