replicaCount: 1

image:
  repository: adeeshadev/lugx-gaming-ui
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

uiIngress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
  paths:
    - path: /
      pathType: Prefix
  tls:
    enabled: false  # You can toggle this to true and set secretName

backendIngress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
  service:
    name: api-gateway
    port: 80
  routes:
    - path: /games
      targetService: game-service-backend
      targetPort: 5001
    - path: /orders
      targetService: order-service-backend
      targetPort: 5004
    - path: /recommendations
      targetService: recommendation-service-backend
      targetPort: 5002
    - path: /track
      targetService: analytics-service-backend
      targetPort: 5003

endpoints:
  analytics: https://api.lugx.minikube.local/track
  orders: https://api.lugx.minikube.local/orders
  games: https://api.lugx.minikube.local/games
  recommendations: https://api.lugx.minikube.local/recommendations


